-- Media by Bela / Supabase
-- Run this in Supabase SQL Editor.
--
-- Authentication is delegated to Supabase Auth. The Cloudflare Worker
-- receives the existing "username" field, maps it to an admin email, and
-- signs in with Supabase Auth using email + password.
--
-- IMPORTANT:
-- Supabase Auth cannot import the old Werkzeug scrypt hash directly.
-- Create the admin user once in Authentication > Users, then insert its
-- Auth user UUID into public.admins as described in README.md.

create extension if not exists pgcrypto;

create table if not exists public.site_settings (
  id integer primary key,
  links jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  username text not null unique,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_groups (
  id uuid primary key default gen_random_uuid(),
  tab text not null check (tab in ('estaticos', 'carrosseis', 'stories')),
  client text not null default '',
  meta text not null default '',
  handle text,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists portfolio_groups_tab_position_idx
  on public.portfolio_groups (tab, position);

create table if not exists public.portfolio_items (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.portfolio_groups(id) on delete cascade,
  position integer not null default 0,
  image text,
  caption text not null default '',
  count integer not null default 0,
  link text,
  images jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists portfolio_items_group_position_idx
  on public.portfolio_items (group_id, position);

alter table public.site_settings enable row level security;
alter table public.admins enable row level security;
alter table public.portfolio_groups enable row level security;
alter table public.portfolio_items enable row level security;

-- Existing local links.json
insert into public.site_settings (id, links)
values (
  1,
  '{
    "instagram": "#",
    "whatsapp": "#",
    "behance": "#",
    "socialMedia": "#",
    "design": "/html/portfolio-design_page.html",
    "portfolioDesign": "/html/portfolio-design_page.html",
    "portfolioSocialMedia": "#"
  }'::jsonb
)
on conflict (id) do update
set links = excluded.links,
    updated_at = now();

-- Existing portfolio.json structure.
do $$
declare
  static_group uuid;
  carousel_group uuid;
begin
  if not exists (select 1 from public.portfolio_groups where tab = 'estaticos') then
    insert into public.portfolio_groups (tab, client, meta, position)
    values ('estaticos', 'Nome do Cliente', 'Categoria · Descrição breve', 0)
    returning id into static_group;

    insert into public.portfolio_items (group_id, position, image, caption)
    values
      (static_group, 0, null, ''),
      (static_group, 1, null, ''),
      (static_group, 2, null, '');
  end if;

  if not exists (select 1 from public.portfolio_groups where tab = 'carrosseis') then
    insert into public.portfolio_groups (tab, client, meta, handle, position)
    values ('carrosseis', 'Nome do Cliente', 'Categoria · Descrição breve', '', 0)
    returning id into carousel_group;

    insert into public.portfolio_items (group_id, position, images, caption)
    values (carousel_group, 0, '[]'::jsonb, '');
  end if;
end $$;

-- Public portfolio images. Reads are public; uploads/deletes are performed
-- only by the Worker using the Supabase server-side Secret Key.
insert into storage.buckets (id, name, public)
values ('portfolio', 'portfolio', true)
on conflict (id) do update set public = true;

-- After creating the Auth user, insert the admin mapping:
--
-- insert into public.admins (auth_user_id, username, email)
-- values ('AUTH_USER_UUID', 'Heitor', 'your-real-email@example.com');
